<a href="https://colab.research.google.com/github/sona3ms/LSTM/blob/main/TENSERFLOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#Initialization of Tensors


In [ ]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#we can specify the shape
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
#2d matrix
x = tf.constant([[1,2,3],[4,5,6]]) #2*3 matrix
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#a 3*3 matrix with values of one
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
x = tf.zeros((3))
print(x)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [ ]:
x = tf.eye(3) # I for identity matrix (eye)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
#uniform distribution
x = tf.random.normal((3,3),mean=0,stddev=1)
x #between -1 and 1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.685211  , -0.36328167,  0.04747138],
       [-1.3904655 ,  0.05651191, -1.6716417 ],
       [ 0.42970836,  0.05928966, -1.3536505 ]], dtype=float32)>

In [ ]:
x = tf.random.uniform((1,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6497978 , 0.50969374, 0.38592362]], dtype=float32)>

In [ ]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
#delta = step
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [ ]:
#convert between different types
#tf.float (16,32,64), tf.int(8,16,64), tf.bool
x= tf.cast(x, dtype=tf.float64)
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [ ]:
x = tf.Variable([1,2,3])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

#Mathematical Operations


In [ ]:
#add
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
z #or z = x + y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
z = tf.subtract(x,y)
z#same as z = x - y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
z = tf.divide(x,y)
z#same as z = x / y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [ ]:
z = tf.multiply(x,y)
z#same as z = x * y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
#dot product
z = tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
z = tf.reduce_sum(x*y,axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
#element wise multiplication
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)# z = x @ y

tf.Tensor(
[[-0.70411694 -1.0772084   1.6824626   1.1871281 ]
 [ 0.36614746  3.4519973  -0.5476543  -1.3439438 ]], shape=(2, 4), dtype=float32)


#Indexing

In [ ]:
x = tf.constant([1,2,3,4,5,6,7,8,9])
print(x[:])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [ ]:
print(x[2:])

tf.Tensor([3 4 5 6 7 8 9], shape=(7,), dtype=int32)


In [ ]:
print(x[1:3])

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [ ]:
print(x[::2])

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)


In [ ]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

#Reshaping

In [ ]:
x = tf.range(9)
#reshape into a 3*3 mathrix
x = tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
#transpose
x = tf.transpose(x, perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

#Building a Neural network

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [ ]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [ ]:
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

In [ ]:
#sequential API (very convenient, not very flexible)
model = keras.Sequential(
    [
        layers.Dense(512, activation='relu'),
        layers.Dense(256,activation='relu'),
        layers.Dense(10),
    ]
)
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = keras.optimizers.Adam(lr=0.001),
    metrics =["accuracy"]
)
model.fit(x_train, y_train, batch_size=32, epochs = 5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32,verbose=2)

Epoch 1/5
1875/1875 - 17s - loss: 0.1855 - accuracy: 0.9444 - 17s/epoch - 9ms/step
Epoch 2/5
1875/1875 - 15s - loss: 0.0791 - accuracy: 0.9752 - 15s/epoch - 8ms/step
Epoch 3/5
1875/1875 - 16s - loss: 0.0555 - accuracy: 0.9820 - 16s/epoch - 8ms/step
Epoch 4/5
1875/1875 - 16s - loss: 0.0389 - accuracy: 0.9873 - 16s/epoch - 8ms/step
Epoch 5/5
1875/1875 - 17s - loss: 0.0316 - accuracy: 0.9899 - 17s/epoch - 9ms/step
313/313 - 2s - loss: 0.0832 - accuracy: 0.9779 - 2s/epoch - 7ms/step


[0.0831795334815979, 0.9779000282287598]